### ISSUE TITLE
not running

### ISSUE THREAD

**Issue by Sheikhlipu123** [Simple2006/DankMemerCoinFarmer#9]
i get 
C:\Users\lipum\Downloads\Compressed\DankMemerCoinFarmer-main\DankMemerCoinFarmer-main>py main.py
Traceback (most recent call last):
  File "C:\Users\lipum\Downloads\Compressed\DankMemerCoinFarmer-main\DankMemerCoinFarmer-main\main.py", line 5, in <module>
    p.start()
  File "C:\Users\lipum\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\lipum\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\lipum\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\lipum\AppData\Local\Programs\Python\Python39\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\lipum\AppData\Local\Programs\Python\Python39\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x00000249D0C6AD30>: attribute lookup <lambda> on __main__ failed

C:\Users\lipum\Downloads\Compressed\DankMemerCoinFarmer-main\DankMemerCoinFarmer-main>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\lipum\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 102, in spawn_main
    source_process = _winapi.OpenProcess(
OSError: [WinError 87] The parameter is incorrect

**Comment by Sheikhlipu123** [comment]
hh i m dumb

**Comment by Sheikhlipu123** [comment]
hh im dumb
